# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk13

# используем режим обычного пользователя для сборки проекта.
sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="815feb70-af50-46aa-b5c3-41cd9d908f16"
# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -mgbardakov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always